/* NextUp Credit Pro - live sign-in (email + password + two-step code).
   No secrets here. The public key in config.js is safe by design; the database rules (RLS) protect the data. */
(function () {
  var C = window.NCP || {}, $ = function (id) { return document.getElementById(id); };
  var box = $('box');
  var st = document.createElement('style');
  st.textContent = '.row.click{cursor:pointer}.row.click:hover,.row.click:focus{background:#f5f8ff;outline:none}select{display:block;width:100%;margin-top:6px;padding:12px;font-size:16px;border:1px solid #c9d2e3;border-radius:10px;background:#fff;box-sizing:border-box}.bar+h1{margin-top:14px}.row.pick{cursor:pointer;align-items:flex-start;justify-content:flex-start;gap:12px}.cb{width:22px;height:22px;margin-top:2px;flex:none}.warn{color:#9a5b00}select.mini{width:auto;margin:0;padding:8px 10px;font-size:14px}input[type=file]{padding:10px}';
  document.head.appendChild(st);

  function el(tag, attrs, kids) {
    var e = document.createElement(tag);
    Object.keys(attrs || {}).forEach(function (k) { if (k === 'text') e.textContent = attrs[k]; else e.setAttribute(k, attrs[k]); });
    (kids || []).forEach(function (c) { e.appendChild(c); });
    return e;
  }
  function show(nodes) { box.textContent = ''; nodes.forEach(function (n) { box.appendChild(n); }); var f = box.querySelector('input'); if (f) f.focus(); }
  function head(t, s) { return [el('img', { src: '../icons/logo.svg', alt: '', width: '48', height: '48' }), el('h1', { text: t }), s ? el('p', { class: 'sub', text: s }) : el('p')]; }
  function msg(t) { var m = $('msg'); if (m) { m.textContent = t || ''; } }
  function field(id, label, type, extra) {
    var i = el('input', Object.assign({ id: id, type: type, required: '', autocomplete: 'off' }, extra || {}));
    return el('label', { for: id }, [document.createTextNode(label), i]);
  }

  if (!C.SUPABASE_URL || !C.SUPABASE_ANON_KEY || !window.supabase) {
    show(head('Live app not connected', 'config.js is missing the Supabase address or key.'));
    return;
  }
  var sb = window.supabase.createClient(C.SUPABASE_URL, C.SUPABASE_ANON_KEY, { auth: { persistSession: true, autoRefreshToken: true } });

  /* ---------- screens ---------- */
  function loginScreen() {
    var f = el('form', { id: 'f', novalidate: '' }, [
      field('em', 'Email', 'email', { autocomplete: 'username', inputmode: 'email' }),
      field('pw', 'Password', 'password', { autocomplete: 'current-password' }),
      el('button', { class: 'btn', type: 'submit', text: 'Sign in' }),
      el('div', { id: 'msg', class: 'msg', role: 'alert' })
    ]);
    show(head('Sign in', 'NextUp Credit Pro').concat([f]));
    f.addEventListener('submit', function (e) {
      e.preventDefault();
      var b = f.querySelector('button'); b.disabled = true; msg('');
      sb.auth.signInWithPassword({ email: $('em').value.trim(), password: $('pw').value }).then(function (r) {
        if (r.error) { b.disabled = false; msg('That email or password did not work.'); return; }
        $('pw').value = ''; afterPassword();
      }).catch(function () { b.disabled = false; msg('Could not reach the server. Check your internet and try again.'); });
    });
  }

  function afterPassword() {
    sb.auth.mfa.getAuthenticatorAssuranceLevel().then(function (a) {
      if (a.error) { fail(a.error); return; }
      if (a.data.currentLevel === 'aal2') return home();
      sb.auth.mfa.listFactors().then(function (l) {
        if (l.error) { fail(l.error); return; }
        var t = (l.data.totp || []).filter(function (x) { return x.status === 'verified'; })[0];
        if (t) codeScreen(t.id); else enrollScreen();
      });
    });
  }

  function enrollScreen() {
    sb.auth.mfa.enroll({ factorType: 'totp', friendlyName: 'Authenticator ' + Date.now() }).then(function (r) {
      if (r.error) { fail(r.error); return; }
      var d = r.data, qr = el('img', { alt: 'QR code to scan with your authenticator app', width: '200', height: '200', class: 'qr' });
      qr.src = d.totp.qr_code; // data: image generated by Supabase
      var sec = el('code', { text: d.totp.secret });
      var f = el('form', { id: 'f', novalidate: '' }, [
        field('cd', '6-digit code from the app', 'text', { inputmode: 'numeric', pattern: '[0-9]*', maxlength: '6', autocomplete: 'one-time-code' }),
        el('button', { class: 'btn', type: 'submit', text: 'Turn on two-step' }),
        el('div', { id: 'msg', class: 'msg', role: 'alert' })
      ]);
      show(head('Set up two-step sign-in', 'Required for everyone who works here.').concat([
        el('p', { class: 'step', text: '1. On your phone, open an authenticator app (Google Authenticator, Microsoft Authenticator or Authy). Scan this code:' }), qr,
        el('p', { class: 'step', text: "Can't scan? Type this key into the app instead:" }), el('p', {}, [sec]),
        el('p', { class: 'step', text: '2. Type the 6-digit number the app shows:' }), f]));
      f.addEventListener('submit', function (e) { e.preventDefault(); verify(d.id, $('cd').value); });
    });
  }

  function codeScreen(factorId) {
    var f = el('form', { id: 'f', novalidate: '' }, [
      field('cd', '6-digit code', 'text', { inputmode: 'numeric', pattern: '[0-9]*', maxlength: '6', autocomplete: 'one-time-code' }),
      el('button', { class: 'btn', type: 'submit', text: 'Verify' }),
      el('div', { id: 'msg', class: 'msg', role: 'alert' })
    ]);
    show(head('Two-step check', 'Open your authenticator app and type the current code.').concat([f]));
    f.addEventListener('submit', function (e) { e.preventDefault(); verify(factorId, $('cd').value); });
  }

  function verify(factorId, code) {
    code = String(code || '').replace(/\s/g, '');
    if (!/^\d{6}$/.test(code)) { msg('Enter the 6 numbers from the app.'); return; }
    var b = box.querySelector('button'); if (b) b.disabled = true;
    sb.auth.mfa.challenge({ factorId: factorId }).then(function (c) {
      if (c.error) { throw c.error; }
      return sb.auth.mfa.verify({ factorId: factorId, challengeId: c.data.id, code: code });
    }).then(function (v) {
      if (v.error) { if (b) b.disabled = false; msg('That code did not work. Wait for a new one and try again.'); return; }
      home();
    }).catch(function () { if (b) b.disabled = false; msg('Could not verify. Try again.'); });
  }

  function home() {
    sb.auth.getUser().then(function (u) {
      if (u.error || !u.data.user) return loginScreen();
      return sb.from('profiles').select('first_name,role,org_id').eq('id', u.data.user.id).maybeSingle().then(function (p) {
        if (p.error || !p.data) {
          show(head('Signed in, but no profile', 'This account is not linked to a business yet. Ask Junior to add you.').concat([signOutBtn()]));
          return;
        }
        var role = String(p.data.role || '');
        if (['owner', 'manager', 'agent'].indexOf(role) < 0) {
          show(head('Client portal coming soon', 'This live app is for the team right now.').concat([signOutBtn()]));
          return;
        }
        dashboard(u.data.user, p.data);
      });
    }).catch(function () { loginScreen(); });
  }

  /* ---------- dashboard: pipeline (clients grouped by stage) + add client ---------- */
  function dashboard(user, prof) {
    box.classList.add('wide');
    var pipe = el('div', { id: 'pipe' });
    var f = el('form', { id: 'f', novalidate: '', class: 'grid' }, [
      field('fn', 'First name', 'text', { maxlength: '100', autocomplete: 'off' }),
      field('ln', 'Last name', 'text', { maxlength: '100', autocomplete: 'off' }),
      field('ce', 'Email (optional)', 'email', { maxlength: '200', required: null }),
      field('cp', 'Phone (optional)', 'tel', { maxlength: '30', required: null }),
      el('button', { class: 'btn', type: 'submit', text: 'Add client' }),
      el('div', { id: 'msg', class: 'msg', role: 'alert' })
    ]);
    ['ce', 'cp'].forEach(function (id) { f.querySelector('#' + id).removeAttribute('required'); });
    var bar = el('div', { class: 'bar' }, [el('div', {}, [el('strong', { text: (prof.first_name || 'Welcome') }), el('span', { class: 'pill', text: prof.role })]), signOutBtn(true)]);
    show([bar, el('h2', { text: 'Pipeline' }), el('p', { class: 'sub', text: 'Use the dropdown on a client to move their stage. Click a client to open their file.' }), pipe, el('h2', { text: 'Add a client' }), f]);

    function load() {
      sb.from('clients').select('id,first_name,last_name,email,phone,stage,created_at').order('created_at', { ascending: false }).limit(300).then(function (r) {
        pipe.textContent = '';
        if (r.error) { pipe.appendChild(el('p', { class: 'sub', text: 'Could not load clients.' })); return; }
        if (!r.data.length) { pipe.appendChild(el('p', { class: 'sub', text: 'No clients yet. Add your first one below.' })); return; }
        STAGES.forEach(function (stg) {
          var rows = r.data.filter(function (c) { return stageName(c.stage) === stg; });
          pipe.appendChild(el('h2', { text: stg + ' (' + rows.length + ')' }));
          var list = el('div', { class: 'list' });
          if (!rows.length) { list.appendChild(el('p', { class: 'sub', text: 'No clients here yet.' })); }
          rows.forEach(function (c) {
            var sel = el('select', { class: 'mini' }, STAGES.map(function (n) {
              var o = el('option', { value: n, text: n }); if (n === stg) o.setAttribute('selected', ''); return o;
            }));
            sel.addEventListener('click', function (e) { e.stopPropagation(); });
            sel.addEventListener('change', function () {
              sel.disabled = true;
              sb.from('clients').update({ stage: sel.value }).eq('id', c.id).then(function (r2) {
                if (r2.error) { sel.disabled = false; return; }
                sb.from('activity_log').insert({ org_id: prof.org_id, actor: user.id, action: 'moved client to ' + sel.value, target: c.id }).then(function () {});
                load();
              });
            });
            var row = el('div', { class: 'row click', role: 'button', tabindex: '0' }, [
              el('div', {}, [el('strong', { text: c.first_name + ' ' + c.last_name }), el('div', { class: 'sub', text: [c.email, c.phone].filter(Boolean).join(' · ') || 'No contact info yet' })]),
              sel]);
            var open = function () { clientFile(user, prof, c.id); };
            row.addEventListener('click', open);
            row.addEventListener('keydown', function (e) { if (e.key === 'Enter' || e.key === ' ') { if (e.target === sel) return; e.preventDefault(); open(); } });
            list.appendChild(row);
          });
          pipe.appendChild(list);
        });
      });
    }
    load();

    f.addEventListener('submit', function (e) {
      e.preventDefault();
      var fn = $('fn').value.trim(), ln = $('ln').value.trim(), em = $('ce').value.trim(), ph = $('cp').value.trim();
      if (!fn || !ln) { msg('Please fill in the first and last name.'); return; }
      if (em && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)) { msg('That email does not look right.'); return; }
      var b = f.querySelector('button'); b.disabled = true; msg('');
      var newId = crypto.randomUUID();
      sb.from('clients').insert({ id: newId, org_id: prof.org_id, assigned_to: user.id, first_name: fn, last_name: ln, email: em || null, phone: ph || null, stage: 'Leads' })
        .then(function (r) {
          b.disabled = false;
          if (r.error) { msg('Could not save. Please try again.'); return; }
          sb.from('activity_log').insert({ org_id: prof.org_id, actor: user.id, action: 'added client', target: newId }).then(function () {});
          f.reset(); msg(''); load();
        });
    });
  }

  /* ---------- client file ---------- */
  var STAGES = ['Leads', 'Consultation Booked', 'Onboarding', 'Ready for disputing', 'Completed / Google Review'];
  function stageName(v) { return (!v || v === 'new' || STAGES.indexOf(v) < 0) ? STAGES[0] : v; }

  function clientFile(user, prof, id) {
    var revealTimer = null;
    function leave() { clearTimeout(revealTimer); dashboard(user, prof); }
    show([el('p', { class: 'sub', text: 'Loading...' })]);
    sb.from('clients').select('id,first_name,last_name,email,phone,address,stage').eq('id', id).maybeSingle().then(function (r) {
      if (r.error || !r.data) { show([el('p', { class: 'sub', text: 'Could not open this client.' }), backBtn()]); return; }
      draw(r.data);
    });
    function backBtn() { var b = el('button', { class: 'link', type: 'button', text: '< Back to clients' }); b.addEventListener('click', leave); return b; }

    function draw(c) {
      var sel = el('select', { id: 'stg' }, STAGES.map(function (n) { var o = el('option', { value: n, text: n }); if (n === stageName(c.stage)) o.setAttribute('selected', ''); return o; }));
      var f = el('form', { id: 'f', novalidate: '', class: 'grid' }, [
        field('fn', 'First name', 'text', { maxlength: '100' }), field('ln', 'Last name', 'text', { maxlength: '100' }),
        field('ce', 'Email', 'email', { maxlength: '200' }), field('cp', 'Phone', 'tel', { maxlength: '30' }),
        field('ca', 'Address', 'text', { maxlength: '300' }),
        el('label', { for: 'stg' }, [document.createTextNode('Stage'), sel]),
        el('button', { class: 'btn', type: 'submit', text: 'Save details' }),
        el('div', { id: 'msg', class: 'msg', role: 'alert' })
      ]);
      ['ce', 'cp', 'ca'].forEach(function (k) { f.querySelector('#' + k).removeAttribute('required'); });
      f.querySelector('#fn').value = c.first_name || ''; f.querySelector('#ln').value = c.last_name || '';
      f.querySelector('#ce').value = c.email || ''; f.querySelector('#cp').value = c.phone || ''; f.querySelector('#ca').value = c.address || '';
      f.addEventListener('submit', function (e) {
        e.preventDefault();
        var fn = $('fn').value.trim(), ln = $('ln').value.trim(), em = $('ce').value.trim();
        if (!fn || !ln) { msg('Please fill in the first and last name.'); return; }
        if (em && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)) { msg('That email does not look right.'); return; }
        var b = f.querySelector('button'); b.disabled = true; msg('');
        sb.from('clients').update({ first_name: fn, last_name: ln, email: em || null, phone: $('cp').value.trim() || null, address: $('ca').value.trim() || null, stage: $('stg').value }).eq('id', id).then(function (r) {
          b.disabled = false;
          if (r.error) { msg('Could not save. Please try again.'); return; }
          sb.from('activity_log').insert({ org_id: prof.org_id, actor: user.id, action: 'updated client', target: id }).then(function () {});
          msg('Saved.'); $('msg').style.color = '#0a7d3c'; h1.textContent = fn + ' ' + ln;
        });
      });

      /* private details: encrypted, hidden until revealed (each reveal is logged) */
      var out = el('p', { class: 'sub', text: 'Hidden. Click Reveal to see the birthdate and SSN last 4.' });
      var rev = el('button', { class: 'btn ghost', type: 'button', text: 'Reveal' });
      rev.addEventListener('click', function () {
        rev.disabled = true;
        sb.rpc('reveal_sensitive', { cid: id }).then(function (r) {
          rev.disabled = false;
          if (r.error) { out.textContent = 'Could not reveal.'; return; }
          var row = (r.data && r.data[0]) || {};
          if (!row.dob && !row.ssn4) { out.textContent = 'Nothing saved yet.'; return; }
          out.textContent = 'Birthdate: ' + (row.dob || '-') + '   SSN last 4: ' + (row.ssn4 || '-') + '   (hides in 30 seconds)';
          clearTimeout(revealTimer);
          revealTimer = setTimeout(function () { out.textContent = 'Hidden. Click Reveal to see the birthdate and SSN last 4.'; }, 30000);
        });
      });
      var sf = el('form', { id: 'sf', novalidate: '', class: 'grid' }, [
        field('bd', 'Birthdate', 'date', {}), field('s4', 'SSN last 4 digits', 'password', { inputmode: 'numeric', maxlength: '4', pattern: '[0-9]*', autocomplete: 'off' }),
        el('button', { class: 'btn', type: 'submit', text: 'Save private details' }),
        el('div', { id: 'smsg', class: 'msg', role: 'alert' })
      ]);
      sf.addEventListener('submit', function (e) {
        e.preventDefault();
        var d = $('bd').value, s4 = $('s4').value.trim(), sm = $('smsg');
        if (!d || !/^\d{4}$/.test(s4)) { sm.style.color = ''; sm.textContent = 'Enter the birthdate and exactly 4 digits. Saving replaces both.'; return; }
        var b = sf.querySelector('button'); b.disabled = true;
        sb.rpc('set_sensitive', { cid: id, dob: d, ssn4: s4 }).then(function (r) {
          b.disabled = false;
          if (r.error) { sm.style.color = ''; sm.textContent = 'Could not save.'; return; }
          $('s4').value = ''; sm.style.color = '#0a7d3c'; sm.textContent = 'Saved and encrypted.';
        });
      });

      var h1 = el('h1', { text: (c.first_name || '') + ' ' + (c.last_name || '') });
      var repBox = el('div', { id: 'repbox' }); var letBox = el('div', { id: 'letbox' }); var othBox = el('div', {}); var monBox = el('div', { id: 'monbox' });
      show([el('div', { class: 'bar' }, [backBtn(), signOutBtn(true)]), h1, f,
        el('h2', { text: 'Private details' }),
        el('p', { class: 'sub', text: 'Stored encrypted. Only revealed on request, and every reveal is recorded in the activity log.' }), out, rev, sf, repBox, letBox, othBox, monBox]);
      if (window.NCPReport) window.NCPReport.mount(repBox, { sb: sb, clientId: id, prof: prof, user: user });
      if (window.NCPLetters) window.NCPLetters.mount(letBox, { sb: sb, clientId: id, prof: prof, user: user });
      if (window.NCPOutbound) window.NCPOutbound.mount(othBox, { sb: sb, clientId: id, prof: prof, user: user });
      if (window.NCPMonitoring) window.NCPMonitoring.mount(monBox, { sb: sb, clientId: id, prof: prof, user: user });
    }
  }

  function signOutBtn(link) {
    var b = el('button', { class: link ? 'link' : 'btn ghost', type: 'button', text: 'Sign out' });
    b.addEventListener('click', function () { sb.auth.signOut().then(loginScreen); });
    return b;
  }
  function fail() { show(head('Something went wrong', 'Please sign in again.').concat([signOutBtn()])); }

  /* ---------- start ---------- */
  sb.auth.getSession().then(function (s) {
    if (s.data && s.data.session) afterPassword(); else loginScreen();
  }).catch(loginScreen);
})();
