/* NextUp Credit Pro - live sign-in (email + password + two-step code).
   No secrets here. The public key in config.js is safe by design; the database rules (RLS) protect the data. */
(function () {
  var C = window.NCP || {}, $ = function (id) { return document.getElementById(id); };
  var box = $('box');

  function el(tag, attrs, kids) {
    var e = document.createElement(tag);
    Object.keys(attrs || {}).forEach(function (k) { if (k === 'text') e.textContent = attrs[k]; else e.setAttribute(k, attrs[k]); });
    (kids || []).forEach(function (c) { e.appendChild(c); });
    return e;
  }
  function show(nodes) { box.textContent = ''; nodes.forEach(function (n) { box.appendChild(n); }); var f = box.querySelector('input'); if (f) f.focus(); }
  function head(t, s) { return [el('img', { src: '../icons/logo.svg', alt: '', width: '48', height: '48' }), el('h1', { text: t }), s ? el('p', { class: 'sub', text: s }) : el('p')]; }
  function msg(t) { var m = $('msg'); if (m) { m.textContent = t || ''; } }
  function field(id, label, type, extra) {
    var i = el('input', Object.assign({ id: id, type: type, required: '', autocomplete: 'off' }, extra || {}));
    return el('label', { for: id }, [document.createTextNode(label), i]);
  }

  if (!C.SUPABASE_URL || !C.SUPABASE_ANON_KEY || !window.supabase) {
    show(head('Live app not connected', 'config.js is missing the Supabase address or key.'));
    return;
  }
  var sb = window.supabase.createClient(C.SUPABASE_URL, C.SUPABASE_ANON_KEY, { auth: { persistSession: true, autoRefreshToken: true } });

  /* ---------- screens ---------- */
  function loginScreen() {
    var f = el('form', { id: 'f', novalidate: '' }, [
      field('em', 'Email', 'email', { autocomplete: 'username', inputmode: 'email' }),
      field('pw', 'Password', 'password', { autocomplete: 'current-password' }),
      el('button', { class: 'btn', type: 'submit', text: 'Sign in' }),
      el('div', { id: 'msg', class: 'msg', role: 'alert' })
    ]);
    show(head('Sign in', 'NextUp Credit Pro').concat([f]));
    f.addEventListener('submit', function (e) {
      e.preventDefault();
      var b = f.querySelector('button'); b.disabled = true; msg('');
      sb.auth.signInWithPassword({ email: $('em').value.trim(), password: $('pw').value }).then(function (r) {
        if (r.error) { b.disabled = false; msg('That email or password did not work.'); return; }
        $('pw').value = ''; afterPassword();
      }).catch(function () { b.disabled = false; msg('Could not reach the server. Check your internet and try again.'); });
    });
  }

  function afterPassword() {
    sb.auth.mfa.getAuthenticatorAssuranceLevel().then(function (a) {
      if (a.error) { fail(a.error); return; }
      if (a.data.currentLevel === 'aal2') return home();
      sb.auth.mfa.listFactors().then(function (l) {
        if (l.error) { fail(l.error); return; }
        var t = (l.data.totp || []).filter(function (x) { return x.status === 'verified'; })[0];
        if (t) codeScreen(t.id); else enrollScreen();
      });
    });
  }

  function enrollScreen() {
    sb.auth.mfa.enroll({ factorType: 'totp', friendlyName: 'Authenticator ' + Date.now() }).then(function (r) {
      if (r.error) { fail(r.error); return; }
      var d = r.data, qr = el('img', { alt: 'QR code to scan with your authenticator app', width: '200', height: '200', class: 'qr' });
      qr.src = d.totp.qr_code; // data: image generated by Supabase
      var sec = el('code', { text: d.totp.secret });
      var f = el('form', { id: 'f', novalidate: '' }, [
        field('cd', '6-digit code from the app', 'text', { inputmode: 'numeric', pattern: '[0-9]*', maxlength: '6', autocomplete: 'one-time-code' }),
        el('button', { class: 'btn', type: 'submit', text: 'Turn on two-step' }),
        el('div', { id: 'msg', class: 'msg', role: 'alert' })
      ]);
      show(head('Set up two-step sign-in', 'Required for everyone who works here.').concat([
        el('p', { class: 'step', text: '1. On your phone, open an authenticator app (Google Authenticator, Microsoft Authenticator or Authy). Scan this code:' }), qr,
        el('p', { class: 'step', text: "Can't scan? Type this key into the app instead:" }), el('p', {}, [sec]),
        el('p', { class: 'step', text: '2. Type the 6-digit number the app shows:' }), f]));
      f.addEventListener('submit', function (e) { e.preventDefault(); verify(d.id, $('cd').value); });
    });
  }

  function codeScreen(factorId) {
    var f = el('form', { id: 'f', novalidate: '' }, [
      field('cd', '6-digit code', 'text', { inputmode: 'numeric', pattern: '[0-9]*', maxlength: '6', autocomplete: 'one-time-code' }),
      el('button', { class: 'btn', type: 'submit', text: 'Verify' }),
      el('div', { id: 'msg', class: 'msg', role: 'alert' })
    ]);
    show(head('Two-step check', 'Open your authenticator app and type the current code.').concat([f]));
    f.addEventListener('submit', function (e) { e.preventDefault(); verify(factorId, $('cd').value); });
  }

  function verify(factorId, code) {
    code = String(code || '').replace(/\s/g, '');
    if (!/^\d{6}$/.test(code)) { msg('Enter the 6 numbers from the app.'); return; }
    var b = box.querySelector('button'); if (b) b.disabled = true;
    sb.auth.mfa.challenge({ factorId: factorId }).then(function (c) {
      if (c.error) { throw c.error; }
      return sb.auth.mfa.verify({ factorId: factorId, challengeId: c.data.id, code: code });
    }).then(function (v) {
      if (v.error) { if (b) b.disabled = false; msg('That code did not work. Wait for a new one and try again.'); return; }
      home();
    }).catch(function () { if (b) b.disabled = false; msg('Could not verify. Try again.'); });
  }

  function home() {
    sb.auth.getUser().then(function (u) {
      if (u.error || !u.data.user) return loginScreen();
      return sb.from('profiles').select('first_name,role,org_id').eq('id', u.data.user.id).maybeSingle().then(function (p) {
        if (p.error || !p.data) {
          show(head('Signed in, but no profile', 'This account is not linked to a business yet. Ask Junior to add you.').concat([signOutBtn()]));
          return;
        }
        var role = String(p.data.role || '');
        if (['owner', 'manager', 'agent'].indexOf(role) < 0) {
          show(head('Client portal coming soon', 'This live app is for the team right now.').concat([signOutBtn()]));
          return;
        }
        dashboard(u.data.user, p.data);
      });
    }).catch(function () { loginScreen(); });
  }

  /* ---------- dashboard: clients list + add client ---------- */
  function dashboard(user, prof) {
    box.classList.add('wide');
    var list = el('div', { id: 'list', class: 'list' });
    var f = el('form', { id: 'f', novalidate: '', class: 'grid' }, [
      field('fn', 'First name', 'text', { maxlength: '100', autocomplete: 'off' }),
      field('ln', 'Last name', 'text', { maxlength: '100', autocomplete: 'off' }),
      field('ce', 'Email (optional)', 'email', { maxlength: '200', required: null }),
      field('cp', 'Phone (optional)', 'tel', { maxlength: '30', required: null }),
      el('button', { class: 'btn', type: 'submit', text: 'Add client' }),
      el('div', { id: 'msg', class: 'msg', role: 'alert' })
    ]);
    ['ce', 'cp'].forEach(function (id) { f.querySelector('#' + id).removeAttribute('required'); });
    var bar = el('div', { class: 'bar' }, [el('div', {}, [el('strong', { text: (prof.first_name || 'Welcome') }), el('span', { class: 'pill', text: prof.role })]), signOutBtn()]);
    show([bar, el('h2', { text: 'Clients' }), list, el('h2', { text: 'Add a client' }), f]);
    box.querySelector('.bar .btn').classList.remove('btn'); box.querySelector('.bar button').className = 'link';

    function load() {
      sb.from('clients').select('id,first_name,last_name,email,phone,stage,created_at').order('created_at', { ascending: false }).limit(200).then(function (r) {
        list.textContent = '';
        if (r.error) { list.appendChild(el('p', { class: 'sub', text: 'Could not load clients.' })); return; }
        if (!r.data.length) { list.appendChild(el('p', { class: 'sub', text: 'No clients yet. Add your first one below.' })); return; }
        r.data.forEach(function (c) {
          list.appendChild(el('div', { class: 'row' }, [
            el('div', {}, [el('strong', { text: c.first_name + ' ' + c.last_name }), el('div', { class: 'sub', text: [c.email, c.phone].filter(Boolean).join(' · ') || 'No contact info yet' })]),
            el('span', { class: 'pill', text: c.stage || 'new' })]));
        });
      });
    }
    load();

    f.addEventListener('submit', function (e) {
      e.preventDefault();
      var fn = $('fn').value.trim(), ln = $('ln').value.trim(), em = $('ce').value.trim(), ph = $('cp').value.trim();
      if (!fn || !ln) { msg('Please fill in the first and last name.'); return; }
      if (em && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)) { msg('That email does not look right.'); return; }
      var b = f.querySelector('button'); b.disabled = true; msg('');
      sb.from('clients').insert({ org_id: prof.org_id, assigned_to: user.id, first_name: fn, last_name: ln, email: em || null, phone: ph || null })
        .select('id').single().then(function (r) {
          b.disabled = false;
          if (r.error) { msg('Could not save. Please try again.'); return; }
          sb.from('activity_log').insert({ org_id: prof.org_id, actor: user.id, action: 'added client', target: r.data.id }).then(function () {});
          f.reset(); msg(''); load();
        });
    });
  }

  function signOutBtn() {
    var b = el('button', { class: 'btn ghost', type: 'button', text: 'Sign out' });
    b.addEventListener('click', function () { sb.auth.signOut().then(loginScreen); });
    return b;
  }
  function fail() { show(head('Something went wrong', 'Please sign in again.').concat([signOutBtn()])); }

  /* ---------- start ---------- */
  sb.auth.getSession().then(function (s) {
    if (s.data && s.data.session) afterPassword(); else loginScreen();
  }).catch(loginScreen);
})();
